- hosts: localhost
  gather_facts: false

  tasks:
    - name: get info on an instance
      google.cloud.gcp_compute_instance_info:
        zone: us-central1-a
        project: totalplay-408405
      register: gcp_instance_info

    - name: Show existing instances
      ansible.builtin.debug:
        msg: >-
              {{
              gcp_instance_info.resources
              | map(attribute='name')
              }}
      
