- name: Restore deleted VMs from VEEAM
  hosts: localhost
  gather_facts: false

  module_defaults:
    ansible.builtin.uri:
      validate_certs: false

  tasks:
    - name: Get info on running instances
      google.cloud.gcp_compute_instance_info:
        zone: us-central1-a
        project: "{{ gcp_project }}"
      register: gcp_instance_info

    - name: Show running instances by name
      ansible.builtin.debug:
        msg: >-
              {{
              gcp_instance_info.resources
              | map(attribute='name')
              }}

    - name: Show running instances by ID
      ansible.builtin.debug:
        msg: >-
              {{
              gcp_instance_info.resources
              | map(attribute='id')
              }}

              
    - name: Log on and get an Auth token from VEEAM backup
      ansible.builtin.uri:
        url: "https://{{ veeam_appliance_ip_port }}/api/v1/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
          x-api-version: "1.3-rev0"
        body:
          grant_type: "password"
          username: "{{ veeam_username }}"
          password: "{{ veeam_password }}"
        body_format: form-urlencoded
        validate_certs: false
      register: veeam_login

    - name: Display veeam login result
      ansible.builtin.set_fact:
        veeam_access_token: "{{ veeam_login.json.access_token }}"

    - name: Get all instances active on VEEAM
      ansible.builtin.uri:
        url: "https://{{ veeam_appliance_ip_port }}/api/v1/vmInstances"
        method: GET
        headers:
          x-api-version: "1.3-rev0"
          Authorization: "Bearer {{ veeam_access_token }}"
        validate_certs: false
      register: veeam_instances

    - name: Print instances active on VEEAM (names only)
      ansible.builtin.debug:
        msg: "{{ veeam_instances.json.data | map(attribute='name') }}"

    - name: Print instances active on VEEAM (full data)
      ansible.builtin.debug:
        msg: "{{ veeam_instances.json.data }}"
        verbosity: 2

    - name: Get all restore points for every instance backed up by VEEAM
      ansible.builtin.uri:
        url: "https://{{ veeam_appliance_ip_port }}/api/v1/vmInstance/restorePoints"
        method: GET
        headers:
          x-api-version: "1.3-rev0"
          Authorization: "Bearer {{ veeam_access_token }}"
        validate_certs: false
      register: veeam_restorepoints
    
    - name: Show information about all restore points
      ansible.builtin.debug:
        msg: >-
              {{
              veeam_restorepoints.json.data
              }}
        verbosity: 2

    - name: Show all vmids that have a backup
      ansible.builtin.debug:
        msg: >-
              {{
              veeam_restorepoints.json.data
              | map(attribute='vmInstanceId')
              | unique
              }}

    # - name: Obtain a list of all vm NAMES that have a backup
    #   ansible.builtin.uri:
    #     url: "https://{{ veeam_appliance_ip_port }}/api/v1/vmInstances/{{ item }}"
    #     method: GET
    #     headers:
    #       x-api-version: "1.3-rev0"
    #       Authorization: "Bearer {{ veeam_access_token }}"
    #     validate_certs: false
    #   loop: "{{ veeam_restorepoints.json.data | map(attribute='vmInstanceId') | unique }}"
    #   register: known_machines_rest_results
        
    # - name: Show all vm NAMES that have a backup
    #   ansible.builtin.debug:
    #     msg: >-
    #       {{ known_machines_rest_results.results
    #         | map(attribute="name")
    #       }}

    - name: Calculate machines to RESTORE (list difference)
      ansible.builtin.set_fact:
        restore_vmid_list: >-
          {{
          ( veeam_restorepoints.json.data | map(attribute='vmInstanceId'))
          | difference(gcp_instance_info.resources | map(attribute='id'))
          }}

    - name: Show restore vmid list
      ansible.builtin.debug:
        var: restore_vmid_list
        verbosity: 2   

    - name: Get latest restorepoints for each vmid
      ansible.builtin.set_fact:
        last_snapshot: >-
          {{ (last_snapshot | default([])) + 
          [
          veeam_restorepoints.json.data | 
          selectattr('type', 'equalto', 'Snapshot') |
          selectattr('vmInstanceId', 'equalto', item) |
          sort(attribute='creationTimeUtc') |
          last 
          ]
          }}
      loop: "{{ restore_vmid_list }}"


    # - name: Get Veeam Service Account that's needed for operating
    #   ansible.builtin.uri:
    #     url: "https://{{ veeam_appliance_ip_port }}/api/v1/serviceAccounts"
    #     method: GET
    #     headers:
    #       x-api-version: "1.3-rev0"
    #       Authorization: "Bearer {{ veeam_access_token }}"
    #     validate_certs: false
    #   register: veeam_serviceaccounts

    # - name: Print service accounts
    #   ansible.builtin.debug:
    #     msg: "{{ veeam_serviceaccounts }}"

    # - name: Do a test restore of the latest restorepoint into machine id 7603165133034585515
    #   ansible.builtin.uri:
    #     url: "https://{{ veeam_appliance_ip_port }}/api/v1/vmInstance/restorePoints/{{ last_snapshot.id }}/restoreInstance"
    #     method: POST
    #     headers:
    #       x-api-version: "1.3-rev0"
    #       Authorization: "Bearer {{ veeam_access_token }}"
    #       Content-Type: application/json
    #     body_format: json
    #     body:
    #       projectId: "qa-itsm-cloud"
    #       # Use first service account that was found
    #       serviceAccountId: "{{ veeam_serviceaccounts.json.data[0].id }}"
          # INTO ORIGINAL LOCATION
      #     restoreToOriginal: true
      #   validate_certs: false
      # register: veeam_restorepoints
