- hosts: localhost
  gather_facts: false

  vars:
    instances:
      - instance-1
      - instance-2
      - instance-3

  tasks:
    - name: get info on an instance
      google.cloud.gcp_compute_instance_info:
        zone: us-central1-a
        # filters:
        #   - name = '*'
        project: totalplay
        auth_kind: serviceaccount
        # service_account_file: "totalplay-408405-183388a2eb3d.json"
      register: gcp_instance_info

    - name: Show missing instances
      ansible.builtin.debug:
        # msg: >- 
        #       {{ 
        #       gcp_instance_info.resources | selectattr('hostname'
        #       | difference(desired_ instances))
        #       }}
        msg: "{{ gcp_instance_info.resources }}"
